### ISSUE TITLE
Elasticsearch container example is failing 

### ISSUE THREAD

**Issue by StephaneBischoff** [markheath/aci-getting-started#1]
Hi,

Elasticsearch container example is failing with error as of June 2019

```
ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```

**Comment by markheath** [comment]
What exact command are you running? I can't get it to run `elasticsearch:latest` at all at the moment - I have to specify a version.
I think it needs `--environment-variables 'discovery.type=single-node'` but annoyingly that gets rejected because it doesn't like the dot in the environment variable name

**Comment by markheath** [comment]
I'm not sure that I actually showed the elasticsearch demo in the Pluralsight course in the end! Maybe it never worked! I think the idea was to just use it as a quick example of running third party software. I guess I could just change the demo to Redis or MongoDb or something.

**Comment by markheath** [comment]
The dot in the environment variable name appears to be a [limitation of ACI](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/container-instances/container-instances-troubleshooting.md#naming-conventions) which is annoying, because that would be a very easy fix to the elasticsearch demo

**Comment by StephaneBischoff** [comment]
Hi,

It seems that with the version of Elasticsearch 6.7.1 (The one I am using), the underlying Linux Host needs to have a particular  **vm.max_map_count** setting otherwise Elasticsearch fails on startup (boot checks). https://social.msdn.microsoft.com/Forums/azure/en-US/d0235991-3b5f-473b-a422-93da07c80ea0/elasticsearch-container-increase-vmmaxmapcount?forum=AzureContainerServices

So, it does not seem possible to run Elasticsearch on Azure Container Instances, which is really a bummer :(

**Comment by insycaOps** [comment]
Hi,
we assembled a elasticsearch and kibana docker image and minimal step-by-step guide for deployment on Azure Container Instance. It's in german but the steps for deployment are easily to understand:
 https://insyca.home.blog/2020/06/02/elasticsearch-und-kibana-docker-images-fur-azure-container-instance-aci/

**Comment by clharman** [comment]
For anyone running into this problem, it is possible to run elasticsearch on ACI!
You can set the single-node option by replacing discovery.type with ES_SETTING_DISCOVERY_TYPE!

This comes from here: https://www.elastic.co/guide/en/elasticsearch/reference/master/docker.html#docker-configuration-methods

This will turn the map error into a warning. It seems that in ACI you cannot actually modify the map settings on the host machine, from the thread here: https://social.msdn.microsoft.com/Forums/azure/en-US/d0235991-3b5f-473b-a422-93da07c80ea0/elasticsearch-container-increase-vmmaxmapcount?forum=AzureContainerServices

Here's my working docker-compose.yaml:
```
version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.6.0
    environment:
      ES_SETTING_DISCOVERY_TYPE: 'single-node'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      ES_SETTING_XPACK_SECURITY_ENABLED: 'false'
      ES_SETTING_XPACK_LICENSE_SELF__GENERATED_TYPE: 'basic'
    volumes:
      - dev-volume:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic
    deploy:
      resources:
        limits:
          memory: 2g
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 5m
    # restart: no # Remove restart for debugging, then you can do docker logs --follow

  kibana:
    image: kibana:8.6.0
    ports:
      - target: 5601
        published: 5601
    environment:
      XPACK_SECURITY_ENABLED: 'false'
    depends_on:
      - elasticsearch
    networks:
      - elastic
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 5m

volumes:
  dev-volume:
    driver: azure_file
    driver_opts:
      share_name: dev-volume
      storage_account_name: mystorageaccount

networks:
  elastic:
    name: elastic
    driver: bridge
```
